# Unified GoReleaser configuration
# Handles GitHub Releases, Homebrew Tap, Snapcraft, and Chocolatey in one pass
version: 2

project_name: promptext

builds:
  - id: default
    binary: promptext
    main: ./cmd/promptext
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.date={{.Date}}

archives:
  - formats: ["tar.gz"]
    format_overrides:
      - goos: windows
        formats: ["zip"]
    name_template: >-
      {{ .ProjectName }}_
      {{- if eq .Os "darwin" }}Darwin
      {{- else if eq .Os "linux" }}Linux
      {{- else if eq .Os "windows" }}Windows
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  use: github
  groups:
    - title: Features
      regexp: '^.*?feat.*?:.*$'
    - title: Bug Fixes
      regexp: '^.*?fix.*?:.*$'
    - title: Others
      order: 999

release:
  github:
    owner: 1broseidon
    name: promptext
  mode: replace
  header: |
    ## Installation

    **Install Scripts (Recommended):**
    ```bash
    # macOS/Linux
    curl -sSL promptext.sh/install | bash

    # Windows PowerShell
    irm promptext.sh/install.ps1 | iex
    ```

    **Go Install:**
    ```bash
    go install github.com/1broseidon/promptext/cmd/promptext@latest
    ```

    **Manual Download:**
    Download binaries for your platform from the Assets section below.

    **Uninstall:**
    ```bash
    curl -sSL promptext.sh/uninstall | bash
    ```

    ---
  footer: |
    **Documentation:** https://promptext.sh

    **Verify Installation:**
    ```bash
    promptext --version
    # or use the alias
    prx --version
    ```
