# GoReleaser Chocolatey Configuration (Experimental)
# Only builds Windows binaries and publishes to Chocolatey
version: 2

project_name: promptext

# Build configuration - Windows only
builds:
  - id: default
    binary: promptext
    main: ./cmd/promptext
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.date={{.Date}}

# Archives for Chocolatey (needs zip files)
archives:
  - id: default
    formats: ["zip"]
    name_template: >-
      {{ .ProjectName }}_
      {{- if eq .Os "windows" }}Windows
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - README.md
      - LICENSE

# Skip checksums and changelog (not needed for choco)
checksum:
  disable: true

changelog:
  disable: true

# Use existing GitHub release (created by stable workflow)
release:
  disable: true
  make_latest: false
  prerelease: auto
  mode: keep-existing

# Chocolatey (EXPERIMENTAL)
chocolateys:
  - name: promptext
    ids:
      - default  # Reference the build id
    title: Promptext
    authors: George Dikeakos
    project_url: https://github.com/1broseidon/promptext
    url_template: "https://github.com/1broseidon/promptext/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    license_url: https://github.com/1broseidon/promptext/blob/main/LICENSE
    copyright: 2024 George Dikeakos
    require_license_acceptance: false
    project_source_url: https://github.com/1broseidon/promptext
    docs_url: https://github.com/1broseidon/promptext#readme
    bug_tracker_url: https://github.com/1broseidon/promptext/issues
    tags: "cli go ai llm token-counter context promptext"
    summary: Smart code context extractor for AI assistants
    description: |
      Promptext analyzes codebases, filters relevant files, estimates token
      usage using tiktoken (GPT-3.5/4 compatible), and provides formatted
      output suitable for AI prompts.

      Features:
      - Smart file filtering with .gitignore support
      - Relevance prioritization with multi-factor scoring
      - Token budget management
      - Multiple output formats (PTX, TOON, Markdown, XML)
      - Accurate token counting using tiktoken
    api_key: "{{ .Env.CHOCOLATEY_API_KEY }}"
    skip_publish: false
