# GoReleaser Snap Configuration (Experimental)
# Only builds and publishes to Snap Store
version: 2

project_name: promptext

# Build configuration
builds:
  - id: default
    binary: promptext
    main: ./cmd/promptext
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.date={{.Date}}

# Skip archives, checksums, and changelog (snap builds from binaries directly)
# Empty archives list skips the archive pipe entirely
archives: []

checksum:
  disable: true

changelog:
  disable: true

# Disable GitHub release
release:
  disable: true

# Snap (EXPERIMENTAL - pending store approval)
snapcrafts:
  - name: promptext
    publish: true
    summary: Smart code context extractor for AI assistants
    description: |
      Promptext analyzes codebases, filters relevant files, estimates token
      usage using tiktoken (GPT-3.5/4 compatible), and provides formatted
      output suitable for AI prompts.
    grade: stable
    confinement: classic
    license: MIT
    apps:
      promptext:
        command: promptext
