package initializer

import (
	"strings"
	"testing"
)

func TestTemplateGenerator_Generate(t *testing.T) {
	tests := []struct {
		name         string
		projectTypes []ProjectType
		includeTests bool
		expectExts   []string
		expectExc    []string
		notExpectExc []string // Patterns that should NOT be in excludes
	}{
		{
			name: "Next.js with tests excluded",
			projectTypes: []ProjectType{
				{Name: "nextjs", Description: "Next.js", Priority: 100},
			},
			includeTests: false,
			expectExts:   []string{".js", ".jsx", ".ts", ".tsx"},
			expectExc:    []string{"node_modules", ".next", "*.test.ts", "*.test.js"},
		},
		{
			name: "Next.js with tests included",
			projectTypes: []ProjectType{
				{Name: "nextjs", Description: "Next.js", Priority: 100},
			},
			includeTests: true,
			expectExts:   []string{".js", ".jsx", ".ts", ".tsx"},
			expectExc:    []string{"node_modules", ".next"},
			notExpectExc: []string{"*.test.ts", "*.test.js"},
		},
		{
			name: "Go project",
			projectTypes: []ProjectType{
				{Name: "go", Description: "Go", Priority: 80},
			},
			includeTests: false,
			expectExts:   []string{".go", ".mod"},
			expectExc:    []string{"vendor", "*_test.go"},
		},
		{
			name: "Django project",
			projectTypes: []ProjectType{
				{Name: "django", Description: "Django", Priority: 100},
			},
			includeTests: false,
			expectExts:   []string{".py", ".html"},
			expectExc:    []string{"__pycache__", "venv", "test_*.py"},
		},
		{
			name: "Mixed Go + Node project",
			projectTypes: []ProjectType{
				{Name: "go", Description: "Go", Priority: 80},
				{Name: "node", Description: "Node.js", Priority: 60},
			},
			includeTests: false,
			expectExts:   []string{".go", ".mod", ".js", ".ts"},
			expectExc:    []string{"vendor", "node_modules", "*_test.go", "*.test.js"},
		},
		{
			name:         "Empty project types",
			projectTypes: []ProjectType{},
			includeTests: false,
			expectExts:   []string{}, // No extensions added for unknown project
			expectExc:    []string{".git", ".svn"}, // Only base excludes
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			generator := NewTemplateGenerator()
			template := generator.Generate(tt.projectTypes, tt.includeTests)

			// Check extensions
			for _, ext := range tt.expectExts {
				found := false
				for _, templateExt := range template.Extensions {
					if templateExt == ext {
						found = true
						break
					}
				}
				if !found {
					t.Errorf("Expected extension %s not found in template. Got: %v", ext, template.Extensions)
				}
			}

			// Check expected excludes
			for _, exc := range tt.expectExc {
				found := false
				for _, templateExc := range template.Excludes {
					if strings.Contains(templateExc, exc) {
						found = true
						break
					}
				}
				if !found {
					t.Errorf("Expected exclude pattern containing %s not found. Got: %v", exc, template.Excludes)
				}
			}

			// Check patterns that should NOT be present
			for _, exc := range tt.notExpectExc {
				for _, templateExc := range template.Excludes {
					if strings.Contains(templateExc, exc) {
						t.Errorf("Pattern %s should not be in excludes (tests included), but found: %s", exc, templateExc)
					}
				}
			}
		})
	}
}

func TestTemplateGenerator_GenerateYAML(t *testing.T) {
	generator := NewTemplateGenerator()

	template := &ConfigTemplate{
		Extensions: []string{".go", ".js", ".ts"},
		Excludes:   []string{"vendor/**", "node_modules/**", "*.test.go"},
		Comments: map[string]string{
			"header":     "Promptext Configuration File",
			"extensions": "File extensions to include",
			"excludes":   "Patterns to exclude",
		},
	}

	yaml := generator.GenerateYAML(template)

	// Check YAML structure
	requiredStrings := []string{
		"# Promptext Configuration File",
		"# Auto-generated by: promptext --init",
		"extensions:",
		"  - .go",
		"  - .js",
		"  - .ts",
		"excludes:",
		"vendor/**",
		"node_modules/**",
		"gitignore: true",
		"use-default-rules: true",
		"format: ptx",
		"verbose: false",
		"debug: false",
	}

	for _, required := range requiredStrings {
		if !strings.Contains(yaml, required) {
			t.Errorf("YAML should contain '%s', but doesn't.\nYAML:\n%s", required, yaml)
		}
	}

	// Verify proper YAML formatting
	lines := strings.Split(yaml, "\n")
	for i, line := range lines {
		// Check that exclude patterns are properly quoted
		if strings.HasPrefix(strings.TrimSpace(line), "- ") && strings.Contains(line, "*") {
			if !strings.Contains(line, `"`) {
				t.Errorf("Line %d with wildcard should be quoted: %s", i+1, line)
			}
		}
	}
}

func TestTemplateGenerator_AllFrameworks(t *testing.T) {
	// Test that all supported frameworks generate valid templates
	frameworks := []string{
		"nextjs", "nuxt", "vite", "vue", "angular", "svelte", "node",
		"go", "django", "flask", "python",
		"rust", "maven", "gradle", "ruby", "php", "laravel", "dotnet",
	}

	generator := NewTemplateGenerator()

	for _, framework := range frameworks {
		t.Run(framework, func(t *testing.T) {
			projectTypes := []ProjectType{
				{Name: framework, Description: framework, Priority: 100},
			}

			template := generator.Generate(projectTypes, false)

			// Verify template has extensions (except for unknown types)
			if len(template.Extensions) == 0 {
				t.Errorf("Framework %s should generate at least one extension", framework)
			}

			// Verify template has excludes
			if len(template.Excludes) == 0 {
				t.Error("Template should always have at least base excludes")
			}

			// Verify YAML generation doesn't panic
			yaml := generator.GenerateYAML(template)
			if len(yaml) == 0 {
				t.Error("Generated YAML should not be empty")
			}

			// Verify base excludes are present
			if !strings.Contains(yaml, ".git") {
				t.Error("Generated YAML should contain base .git exclude")
			}
		})
	}
}

func TestTemplateGenerator_Deduplication(t *testing.T) {
	// Test that duplicate extensions and excludes are handled correctly
	generator := NewTemplateGenerator()

	// Create scenario where both Go and Node are detected (both add .js)
	projectTypes := []ProjectType{
		{Name: "go", Description: "Go", Priority: 80},
		{Name: "node", Description: "Node.js", Priority: 60},
	}

	template := generator.Generate(projectTypes, false)

	// Count occurrences of each extension
	extCount := make(map[string]int)
	for _, ext := range template.Extensions {
		extCount[ext]++
	}

	// Verify no duplicates
	for ext, count := range extCount {
		if count > 1 {
			t.Errorf("Extension %s appears %d times (should be deduplicated)", ext, count)
		}
	}

	// Count occurrences of each exclude pattern
	excCount := make(map[string]int)
	for _, exc := range template.Excludes {
		excCount[exc]++
	}

	// Verify no duplicates
	for exc, count := range excCount {
		if count > 1 {
			t.Errorf("Exclude pattern %s appears %d times (should be deduplicated)", exc, count)
		}
	}
}
